name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Kích hoạt khi push vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Phiên bản Node.js

      - name: Install dependencies
        run: npm install # Bỏ qua nếu không dùng npm

      - name: Build project
        run: npm run build # Lệnh build của bạn (nếu có)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Thư mục cần deploy
